server:
  port: 8000

student:
  id: 1003
  name: tom
  age: 30
  desc: ${student.name} is a student, ${student.age} years old this year
  
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile
spring:
  profiles:
    active: dev